config/routes.rb
Rails.application.routes.draw do
  resources :wishlists
  resources :users
  get 'foursquare/callback'

  resources :sessions

  post 'wishlists/delete', to: 'wishlists#delete', as: 'remove_wishlist'
  root "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/foursquare_controller.rb
class FoursquareController < ApplicationController
  def callback
    session[:access_token] = FoursquareService::API.new.get_auth_token(params[:code])
    user_response = FoursquareService::API.new.get_user(session[:access_token])

    username = user_response['response']['user']['firstName']
    foursquare_id = user_response['response']['user']['id']
    photo = user_response['response']['user']['photo']['prefix'] + '100x100' + user_response['response']['user']['photo']['suffix']

    user = User.find_or_create_by(username: username, foursquare_id: foursquare_id, photo: photo)
    session[:user_id] = user.id
    redirect_to user_url(user)

  rescue JSON::ParserError => e
    Rails.logger.error(e.message)
    return false
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: [:show, :edit, :update, :destroy]

  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.all
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
  end

  # GET /sessions/new
  def new
    @auth_url = FoursquareService::API.new.get_auth_url
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = Session.new(session_params)
    respond_to do |format|
      if @session.save
        format.html { redirect_to @session, notice: 'Session was successfully created.' }
        format.json { render :show, status: :created, location: @session }
      else
        format.html { render :new }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessions/1
  # PATCH/PUT /sessions/1.json
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { redirect_to @session, notice: 'Session was successfully updated.' }
        format.json { render :show, status: :ok, location: @session }
      else
        format.html { render :edit }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    session[:user_id] = nil
    session[:access_token] = nil

    redirect_to new_session_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session
      # @session = Session.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_params
      params.fetch(:session, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
    @wishlists = Wishlist.where(user_id: @user.id).to_a || []
    wishlist_ids = @wishlists.pluck(:venue_id)

    response = FoursquareService::API.new.get_recent_checkins(session[:access_token])
    @recents = []

    response["response"]["recent"].each do |recent|
      id = recent['venue']['id']
      unless wishlist_ids.include? id
        recent_item = Hash.new
        recent_item[:venue_id] = id
        recent_item[:venue_name] = recent['venue']['name']
        recent_item[:user_name] = "#{recent['user']['firstName']} #{recent['user']['lastName']}"
        recent_item[:user_photo] = "#{recent['user']['photo']['prefix'] + '100x100' + recent['user']['photo']['suffix']}"

        # get venue photo
        venue_id = recent['venue']['id']

        venue_response = FoursquareService::API.new.get_venue(venue_id, session[:access_token])
        if venue_response['response']['venue']['photos']['count'] != 0
          prefix = venue_response['response']['venue']['photos']['groups'][0]['items'][0]['prefix']
          suffix = venue_response['response']['venue']['photos']['groups'][0]['items'][0]['suffix']

          recent_item[:venue_photo] = "#{prefix}300x300#{suffix}"
        else
          recent_item[:venue_photo] = "https://www.socabelec.co.ke/wp-content/uploads/no-photo-14.jpg"
        end

        @recents << recent_item
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    set_user
    @wishlists = Wishlist.where(user_id: @user.id) || []
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    wishlist = Wishlist.new(wishlist_params)
    wishlist.venue_name = wishlist.venue_name.strip
    wishlist.user_id = current_user.id

    respond_to do |format|
      if wishlist.save
        response = render_to_string('wishlists/_wishlist_card', :layout => false, :locals => { :wishlist => wishlist })
        format.json { render json:{ html_data: response } }
      else
        # format.html { render :new }
        format.json { render json: wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    wishlist = Wishlist.where(venue_id: params[:venue_id]).first
    wishlist.destroy

    respond_to do |format|
      if wishlist.destroyed?
          venue = getVenue(wishlist.venue_id)
          response = render_to_string('users/_recent_card', :layout => false, :locals => { :recent => venue })
          format.json { render json:{ html_data: response } }
        else
          format.json { render json: wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def getVenue(venue_id)
    response = FoursquareService::API.new.get_recent_checkins(session[:access_token])
    recent_item = Hash.new

    response["response"]["recent"].each do |recent|
      id = recent['venue']['id']
      if id == venue_id
        recent_item[:venue_id] = id
        recent_item[:venue_name] = recent['venue']['name']
        recent_item[:user_name] = "#{recent['user']['firstName']} #{recent['user']['lastName']}"
        recent_item[:user_photo] = "#{recent['user']['photo']['prefix'] + '100x100' + recent['user']['photo']['suffix']}"

        # get venue photo
        venue_id = recent['venue']['id']

        venue_response = FoursquareService::API.new.get_venue(venue_id, session[:access_token])
        if venue_response['response']['venue']['photos']['count'] != 0
          prefix = venue_response['response']['venue']['photos']['groups'][0]['items'][0]['prefix']
          suffix = venue_response['response']['venue']['photos']['groups'][0]['items'][0]['suffix']

          recent_item[:venue_photo] = "#{prefix}300x300#{suffix}"
        else
          recent_item[:venue_photo] = "https://www.socabelec.co.ke/wp-content/uploads/no-photo-14.jpg"
        end
      end
    end

    recent_item
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      # @wishlist = Wishlist.find(params[:id])
    end

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.permit(:venue_name, :venue_photo, :venue_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !session[:access_token].blank?
  end
end

app/helpers/foursquare_helper.rb
module FoursquareHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/foursquare/callback.html.erb
<h1>Foursquare#callback</h1>
<p>Find me in app/views/foursquare/callback.html.erb</p>

<p><%= "#{@response}" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JayaWishlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Cagliostro|Limelight|Montserrat|Raleway" rel="stylesheet">
  </head>

  <body>
    <% if logged_in? %>

      <div class="header">
        <div class="header-title">
          <h1 class="title">Wishlister</h1>
        </div>
        <div class="logged-user">
          <span class="logged-user-name"> Welcome <%= "#{@user.username}" %> </span>

          <img class="logged-user-image rounded-circle" src=<%= "#{@user.photo}" %>>
        </div>
        <div class="logout-link">
          <p><%= link_to "Log out", session_url, method: "DELETE", :id => "log-io" %></p>
        </div>
      </div>

    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_recent.html.erb
<p id="notice"><%= notice %></p>

<p class="title-small">Recent</p>
<div class="separator"></div>

<div class="row" id="recent-items">
  <% if @recents.any? %>
    <% @recents.each do |recent| %>
      <%= render 'recent_card', recent: recent %>
    <% end %>
   <% else %>
    <h2 class="no-items">No recent venues from firends yet!</h2>
  <% end %>
</div>

<script>
  function addVenue(a) {
    var venue_id_array = a.id.split('_');
    var venue_id = venue_id_array[venue_id_array.length-1];
    var venue_name = $('#venue_name_' + venue_id).text();
    var venue_photo = $('#venue_photo_' + venue_id)[0].currentSrc;

    $.ajax({
            url:"<%= wishlists_url %>",
            data: { venue_id: venue_id,
                    venue_name: venue_name,
                    venue_photo: venue_photo },
            method: "POST",
            success:function(data) {
              // inject wishlist card with the new venue;
              $('#wishlist-items').append(data['html_data']);
              $('.no-items').hide();
              $(a.parentElement.parentElement.parentElement).hide("slow");
            },
            error: function(jqXHR, textStatus, errorThrown){
                console.error(errorThrown);
            }
        });
  }
</script>

app/views/users/_recent_card.html.erb
<div class="panel panel-default">
  <div class="panel-thumbnail" >
    <img src=<%= "#{recent[:venue_photo]}" %> class="panel-thumbnail" id=<%= "venue_photo_#{recent[:venue_id]}" %>>
  </div>
  <div class="panel-body">
    <h3 id=<%= "venue_name_#{recent[:venue_id]}" %>>
      <img src="https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678092-sign-add-128.png" height="40px" width="40px" id=<%= "add_venue_#{recent[:venue_id]}" %> onClick="addVenue(this);" class="pointer" />
      <%= "#{recent[:venue_name]}" %>
    </h3>
    <div class="separator"></div>
    <p class="user-info">
      <img src=<%= "#{recent[:user_photo]}" %> height="70px" width="70px" class="rounded-circle img-margin">
      <%= "#{recent[:user_name]}" %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'wishlists/index', whishlist: @whishlists %>

<%= render 'recent', user: @user %>

app/views/wishlists/_index.html.erb
<p id="notice"><%= notice %></p>

<p class="title-small">Wishlist</p>
<div class="separator"></div>

<div class="row" id="wishlist-items">
  <% if @wishlists.any? %>
    <% @wishlists.each do |wishlist| %>
        <%= render 'wishlists/wishlist_card', wishlist: wishlist %>
    <% end %>
  <% else %>
    <h2 class="no-items">No wishes yet!</h2>
  <% end %>
</div>

<script>
  function removeVenue(a) {
    if (confirm('Are you sure?')) {
      var venue_id_array = a.id.split('_');
      var venue_id = venue_id_array[venue_id_array.length-1];

      $.ajax({
            url:"<%= remove_wishlist_url() %>",
            data: { venue_id: venue_id },
            method: "POST",
            success:function(data) {
              $('#recent-items').prepend(data['html_data']);
              $('.no-items').hide();
              $(a.parentElement.parentElement.parentElement).hide("slow");
            },
            error: function(jqXHR, textStatus, errorThrown){
                console.error(errorThrown);
            }
        });
      }
  }
</script>

app/views/wishlists/_wishlist_card.html.erb
<div class="panel panel-default">
  <div class="panel-thumbnail" >
    <img src=<%= "#{wishlist.venue_photo}" %> class="panel-thumbnail" id=<%= "venue_photo_#{wishlist.venue_id}" %>>
  </div>
  <div class="panel-body">
    <h3 id=<%= "venue_name_#{wishlist.venue_id}" %>>
      <img src="https://cdn2.iconfinder.com/data/icons/round-interface-1/217/50-512.png" height="40px" width="40px" id=<%= "remove_venue_#{wishlist.venue_id}" %> onClick="removeVenue(this);" class="pointer" />
      <%= "#{wishlist.venue_name}" %>
    </h3>
  </div>
</div>